// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateFileHook.proto

#include "CreateFileHook.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace CreateFileHook {
class EmptyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Empty> _instance;
} _Empty_default_instance_;
class ShouldSendPathDataRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ShouldSendPathDataRequest> _instance;
} _ShouldSendPathDataRequest_default_instance_;
class ShouldSendPathDataReplyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ShouldSendPathDataReply> _instance;
} _ShouldSendPathDataReply_default_instance_;
class SendPathDataRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SendPathDataRequest> _instance;
} _SendPathDataRequest_default_instance_;
class SendPathDataReplyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SendPathDataReply> _instance;
} _SendPathDataReply_default_instance_;
}  // namespace CreateFileHook
static void InitDefaultsscc_info_Empty_CreateFileHook_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CreateFileHook::_Empty_default_instance_;
    new (ptr) ::CreateFileHook::Empty();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CreateFileHook::Empty::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Empty_CreateFileHook_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Empty_CreateFileHook_2eproto}, {}};

static void InitDefaultsscc_info_SendPathDataReply_CreateFileHook_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CreateFileHook::_SendPathDataReply_default_instance_;
    new (ptr) ::CreateFileHook::SendPathDataReply();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CreateFileHook::SendPathDataReply::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SendPathDataReply_CreateFileHook_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SendPathDataReply_CreateFileHook_2eproto}, {}};

static void InitDefaultsscc_info_SendPathDataRequest_CreateFileHook_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CreateFileHook::_SendPathDataRequest_default_instance_;
    new (ptr) ::CreateFileHook::SendPathDataRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CreateFileHook::SendPathDataRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SendPathDataRequest_CreateFileHook_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SendPathDataRequest_CreateFileHook_2eproto}, {}};

static void InitDefaultsscc_info_ShouldSendPathDataReply_CreateFileHook_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CreateFileHook::_ShouldSendPathDataReply_default_instance_;
    new (ptr) ::CreateFileHook::ShouldSendPathDataReply();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CreateFileHook::ShouldSendPathDataReply::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ShouldSendPathDataReply_CreateFileHook_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ShouldSendPathDataReply_CreateFileHook_2eproto}, {}};

static void InitDefaultsscc_info_ShouldSendPathDataRequest_CreateFileHook_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CreateFileHook::_ShouldSendPathDataRequest_default_instance_;
    new (ptr) ::CreateFileHook::ShouldSendPathDataRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CreateFileHook::ShouldSendPathDataRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ShouldSendPathDataRequest_CreateFileHook_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ShouldSendPathDataRequest_CreateFileHook_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_CreateFileHook_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_CreateFileHook_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_CreateFileHook_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_CreateFileHook_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::ShouldSendPathDataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::ShouldSendPathDataRequest, path_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::ShouldSendPathDataReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::ShouldSendPathDataReply, should_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::SendPathDataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::SendPathDataRequest, oldpath_),
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::SendPathDataRequest, newpath_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CreateFileHook::SendPathDataReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CreateFileHook::Empty)},
  { 5, -1, sizeof(::CreateFileHook::ShouldSendPathDataRequest)},
  { 11, -1, sizeof(::CreateFileHook::ShouldSendPathDataReply)},
  { 17, -1, sizeof(::CreateFileHook::SendPathDataRequest)},
  { 24, -1, sizeof(::CreateFileHook::SendPathDataReply)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CreateFileHook::_Empty_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CreateFileHook::_ShouldSendPathDataRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CreateFileHook::_ShouldSendPathDataReply_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CreateFileHook::_SendPathDataRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CreateFileHook::_SendPathDataReply_default_instance_),
};

const char descriptor_table_protodef_CreateFileHook_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024CreateFileHook.proto\022\016CreateFileHook\"\007"
  "\n\005Empty\")\n\031ShouldSendPathDataRequest\022\014\n\004"
  "path\030\001 \001(\t\")\n\027ShouldSendPathDataReply\022\016\n"
  "\006should\030\001 \001(\010\"7\n\023SendPathDataRequest\022\017\n\007"
  "oldPath\030\001 \001(\t\022\017\n\007newPath\030\002 \001(\t\"\023\n\021SendPa"
  "thDataReply2\211\002\n\007Greeter\022X\n\014SendPathData\022"
  "#.CreateFileHook.SendPathDataRequest\032!.C"
  "reateFileHook.SendPathDataReply\"\000\022f\n\016Sho"
  "uldSendPath\022).CreateFileHook.ShouldSendP"
  "athDataRequest\032\'.CreateFileHook.ShouldSe"
  "ndPathDataReply\"\000\022<\n\nClearPaths\022\025.Create"
  "FileHook.Empty\032\025.CreateFileHook.Empty\"\000b"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_CreateFileHook_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_CreateFileHook_2eproto_sccs[5] = {
  &scc_info_Empty_CreateFileHook_2eproto.base,
  &scc_info_SendPathDataReply_CreateFileHook_2eproto.base,
  &scc_info_SendPathDataRequest_CreateFileHook_2eproto.base,
  &scc_info_ShouldSendPathDataReply_CreateFileHook_2eproto.base,
  &scc_info_ShouldSendPathDataRequest_CreateFileHook_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_CreateFileHook_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CreateFileHook_2eproto = {
  false, false, descriptor_table_protodef_CreateFileHook_2eproto, "CreateFileHook.proto", 487,
  &descriptor_table_CreateFileHook_2eproto_once, descriptor_table_CreateFileHook_2eproto_sccs, descriptor_table_CreateFileHook_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_CreateFileHook_2eproto::offsets,
  file_level_metadata_CreateFileHook_2eproto, 5, file_level_enum_descriptors_CreateFileHook_2eproto, file_level_service_descriptors_CreateFileHook_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_CreateFileHook_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_CreateFileHook_2eproto)), true);
namespace CreateFileHook {

// ===================================================================

void Empty::InitAsDefaultInstance() {
}
class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CreateFileHook.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CreateFileHook.Empty)
}

void Empty::SharedCtor() {
}

Empty::~Empty() {
  // @@protoc_insertion_point(destructor:CreateFileHook.Empty)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Empty::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Empty::ArenaDtor(void* object) {
  Empty* _this = reinterpret_cast< Empty* >(object);
  (void)_this;
}
void Empty::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Empty::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Empty& Empty::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Empty_CreateFileHook_2eproto.base);
  return *internal_default_instance();
}


void Empty::Clear() {
// @@protoc_insertion_point(message_clear_start:CreateFileHook.Empty)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Empty::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Empty::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CreateFileHook.Empty)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CreateFileHook.Empty)
  return target;
}

size_t Empty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CreateFileHook.Empty)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Empty::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CreateFileHook.Empty)
  GOOGLE_DCHECK_NE(&from, this);
  const Empty* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Empty>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CreateFileHook.Empty)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CreateFileHook.Empty)
    MergeFrom(*source);
  }
}

void Empty::MergeFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CreateFileHook.Empty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void Empty::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CreateFileHook.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Empty::CopyFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CreateFileHook.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Empty::IsInitialized() const {
  return true;
}

void Empty::InternalSwap(Empty* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ShouldSendPathDataRequest::InitAsDefaultInstance() {
}
class ShouldSendPathDataRequest::_Internal {
 public:
};

ShouldSendPathDataRequest::ShouldSendPathDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CreateFileHook.ShouldSendPathDataRequest)
}
ShouldSendPathDataRequest::ShouldSendPathDataRequest(const ShouldSendPathDataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path().empty()) {
    path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_path(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:CreateFileHook.ShouldSendPathDataRequest)
}

void ShouldSendPathDataRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ShouldSendPathDataRequest_CreateFileHook_2eproto.base);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ShouldSendPathDataRequest::~ShouldSendPathDataRequest() {
  // @@protoc_insertion_point(destructor:CreateFileHook.ShouldSendPathDataRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ShouldSendPathDataRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ShouldSendPathDataRequest::ArenaDtor(void* object) {
  ShouldSendPathDataRequest* _this = reinterpret_cast< ShouldSendPathDataRequest* >(object);
  (void)_this;
}
void ShouldSendPathDataRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ShouldSendPathDataRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ShouldSendPathDataRequest& ShouldSendPathDataRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ShouldSendPathDataRequest_CreateFileHook_2eproto.base);
  return *internal_default_instance();
}


void ShouldSendPathDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:CreateFileHook.ShouldSendPathDataRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShouldSendPathDataRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CreateFileHook.ShouldSendPathDataRequest.path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ShouldSendPathDataRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CreateFileHook.ShouldSendPathDataRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CreateFileHook.ShouldSendPathDataRequest.path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CreateFileHook.ShouldSendPathDataRequest)
  return target;
}

size_t ShouldSendPathDataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CreateFileHook.ShouldSendPathDataRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ShouldSendPathDataRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CreateFileHook.ShouldSendPathDataRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ShouldSendPathDataRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ShouldSendPathDataRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CreateFileHook.ShouldSendPathDataRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CreateFileHook.ShouldSendPathDataRequest)
    MergeFrom(*source);
  }
}

void ShouldSendPathDataRequest::MergeFrom(const ShouldSendPathDataRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CreateFileHook.ShouldSendPathDataRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.path().size() > 0) {
    _internal_set_path(from._internal_path());
  }
}

void ShouldSendPathDataRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CreateFileHook.ShouldSendPathDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ShouldSendPathDataRequest::CopyFrom(const ShouldSendPathDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CreateFileHook.ShouldSendPathDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShouldSendPathDataRequest::IsInitialized() const {
  return true;
}

void ShouldSendPathDataRequest::InternalSwap(ShouldSendPathDataRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  path_.Swap(&other->path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata ShouldSendPathDataRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ShouldSendPathDataReply::InitAsDefaultInstance() {
}
class ShouldSendPathDataReply::_Internal {
 public:
};

ShouldSendPathDataReply::ShouldSendPathDataReply(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CreateFileHook.ShouldSendPathDataReply)
}
ShouldSendPathDataReply::ShouldSendPathDataReply(const ShouldSendPathDataReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  should_ = from.should_;
  // @@protoc_insertion_point(copy_constructor:CreateFileHook.ShouldSendPathDataReply)
}

void ShouldSendPathDataReply::SharedCtor() {
  should_ = false;
}

ShouldSendPathDataReply::~ShouldSendPathDataReply() {
  // @@protoc_insertion_point(destructor:CreateFileHook.ShouldSendPathDataReply)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ShouldSendPathDataReply::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ShouldSendPathDataReply::ArenaDtor(void* object) {
  ShouldSendPathDataReply* _this = reinterpret_cast< ShouldSendPathDataReply* >(object);
  (void)_this;
}
void ShouldSendPathDataReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ShouldSendPathDataReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ShouldSendPathDataReply& ShouldSendPathDataReply::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ShouldSendPathDataReply_CreateFileHook_2eproto.base);
  return *internal_default_instance();
}


void ShouldSendPathDataReply::Clear() {
// @@protoc_insertion_point(message_clear_start:CreateFileHook.ShouldSendPathDataReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  should_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShouldSendPathDataReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool should = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          should_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ShouldSendPathDataReply::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CreateFileHook.ShouldSendPathDataReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool should = 1;
  if (this->should() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_should(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CreateFileHook.ShouldSendPathDataReply)
  return target;
}

size_t ShouldSendPathDataReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CreateFileHook.ShouldSendPathDataReply)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool should = 1;
  if (this->should() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ShouldSendPathDataReply::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CreateFileHook.ShouldSendPathDataReply)
  GOOGLE_DCHECK_NE(&from, this);
  const ShouldSendPathDataReply* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ShouldSendPathDataReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CreateFileHook.ShouldSendPathDataReply)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CreateFileHook.ShouldSendPathDataReply)
    MergeFrom(*source);
  }
}

void ShouldSendPathDataReply::MergeFrom(const ShouldSendPathDataReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CreateFileHook.ShouldSendPathDataReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.should() != 0) {
    _internal_set_should(from._internal_should());
  }
}

void ShouldSendPathDataReply::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CreateFileHook.ShouldSendPathDataReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ShouldSendPathDataReply::CopyFrom(const ShouldSendPathDataReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CreateFileHook.ShouldSendPathDataReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShouldSendPathDataReply::IsInitialized() const {
  return true;
}

void ShouldSendPathDataReply::InternalSwap(ShouldSendPathDataReply* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(should_, other->should_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShouldSendPathDataReply::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SendPathDataRequest::InitAsDefaultInstance() {
}
class SendPathDataRequest::_Internal {
 public:
};

SendPathDataRequest::SendPathDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CreateFileHook.SendPathDataRequest)
}
SendPathDataRequest::SendPathDataRequest(const SendPathDataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  oldpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_oldpath().empty()) {
    oldpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_oldpath(),
      GetArena());
  }
  newpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_newpath().empty()) {
    newpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_newpath(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:CreateFileHook.SendPathDataRequest)
}

void SendPathDataRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SendPathDataRequest_CreateFileHook_2eproto.base);
  oldpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  newpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SendPathDataRequest::~SendPathDataRequest() {
  // @@protoc_insertion_point(destructor:CreateFileHook.SendPathDataRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SendPathDataRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  oldpath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  newpath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SendPathDataRequest::ArenaDtor(void* object) {
  SendPathDataRequest* _this = reinterpret_cast< SendPathDataRequest* >(object);
  (void)_this;
}
void SendPathDataRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SendPathDataRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SendPathDataRequest& SendPathDataRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SendPathDataRequest_CreateFileHook_2eproto.base);
  return *internal_default_instance();
}


void SendPathDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:CreateFileHook.SendPathDataRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  oldpath_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  newpath_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendPathDataRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string oldPath = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_oldpath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CreateFileHook.SendPathDataRequest.oldPath"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string newPath = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_newpath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CreateFileHook.SendPathDataRequest.newPath"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SendPathDataRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CreateFileHook.SendPathDataRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string oldPath = 1;
  if (this->oldpath().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_oldpath().data(), static_cast<int>(this->_internal_oldpath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CreateFileHook.SendPathDataRequest.oldPath");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_oldpath(), target);
  }

  // string newPath = 2;
  if (this->newpath().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_newpath().data(), static_cast<int>(this->_internal_newpath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CreateFileHook.SendPathDataRequest.newPath");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_newpath(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CreateFileHook.SendPathDataRequest)
  return target;
}

size_t SendPathDataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CreateFileHook.SendPathDataRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string oldPath = 1;
  if (this->oldpath().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_oldpath());
  }

  // string newPath = 2;
  if (this->newpath().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_newpath());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SendPathDataRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CreateFileHook.SendPathDataRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SendPathDataRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SendPathDataRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CreateFileHook.SendPathDataRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CreateFileHook.SendPathDataRequest)
    MergeFrom(*source);
  }
}

void SendPathDataRequest::MergeFrom(const SendPathDataRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CreateFileHook.SendPathDataRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.oldpath().size() > 0) {
    _internal_set_oldpath(from._internal_oldpath());
  }
  if (from.newpath().size() > 0) {
    _internal_set_newpath(from._internal_newpath());
  }
}

void SendPathDataRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CreateFileHook.SendPathDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SendPathDataRequest::CopyFrom(const SendPathDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CreateFileHook.SendPathDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendPathDataRequest::IsInitialized() const {
  return true;
}

void SendPathDataRequest::InternalSwap(SendPathDataRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  oldpath_.Swap(&other->oldpath_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  newpath_.Swap(&other->newpath_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata SendPathDataRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SendPathDataReply::InitAsDefaultInstance() {
}
class SendPathDataReply::_Internal {
 public:
};

SendPathDataReply::SendPathDataReply(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CreateFileHook.SendPathDataReply)
}
SendPathDataReply::SendPathDataReply(const SendPathDataReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CreateFileHook.SendPathDataReply)
}

void SendPathDataReply::SharedCtor() {
}

SendPathDataReply::~SendPathDataReply() {
  // @@protoc_insertion_point(destructor:CreateFileHook.SendPathDataReply)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SendPathDataReply::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SendPathDataReply::ArenaDtor(void* object) {
  SendPathDataReply* _this = reinterpret_cast< SendPathDataReply* >(object);
  (void)_this;
}
void SendPathDataReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SendPathDataReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SendPathDataReply& SendPathDataReply::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SendPathDataReply_CreateFileHook_2eproto.base);
  return *internal_default_instance();
}


void SendPathDataReply::Clear() {
// @@protoc_insertion_point(message_clear_start:CreateFileHook.SendPathDataReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendPathDataReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SendPathDataReply::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CreateFileHook.SendPathDataReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CreateFileHook.SendPathDataReply)
  return target;
}

size_t SendPathDataReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CreateFileHook.SendPathDataReply)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SendPathDataReply::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CreateFileHook.SendPathDataReply)
  GOOGLE_DCHECK_NE(&from, this);
  const SendPathDataReply* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SendPathDataReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CreateFileHook.SendPathDataReply)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CreateFileHook.SendPathDataReply)
    MergeFrom(*source);
  }
}

void SendPathDataReply::MergeFrom(const SendPathDataReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CreateFileHook.SendPathDataReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SendPathDataReply::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CreateFileHook.SendPathDataReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SendPathDataReply::CopyFrom(const SendPathDataReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CreateFileHook.SendPathDataReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendPathDataReply::IsInitialized() const {
  return true;
}

void SendPathDataReply::InternalSwap(SendPathDataReply* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendPathDataReply::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CreateFileHook
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CreateFileHook::Empty* Arena::CreateMaybeMessage< ::CreateFileHook::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CreateFileHook::Empty >(arena);
}
template<> PROTOBUF_NOINLINE ::CreateFileHook::ShouldSendPathDataRequest* Arena::CreateMaybeMessage< ::CreateFileHook::ShouldSendPathDataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CreateFileHook::ShouldSendPathDataRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::CreateFileHook::ShouldSendPathDataReply* Arena::CreateMaybeMessage< ::CreateFileHook::ShouldSendPathDataReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CreateFileHook::ShouldSendPathDataReply >(arena);
}
template<> PROTOBUF_NOINLINE ::CreateFileHook::SendPathDataRequest* Arena::CreateMaybeMessage< ::CreateFileHook::SendPathDataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CreateFileHook::SendPathDataRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::CreateFileHook::SendPathDataReply* Arena::CreateMaybeMessage< ::CreateFileHook::SendPathDataReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CreateFileHook::SendPathDataReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
