// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: blink/LinkCommand.proto

#include "blink/LinkCommand.pb.h"
#include "blink/LinkCommand.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace LinkCommand {

static const char* Greeter_method_names[] = {
  "/LinkCommand.Greeter/Compile",
  "/LinkCommand.Greeter/ShouldSendPathData",
  "/LinkCommand.Greeter/SendPathData",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Compile_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ShouldSendPathData_(Greeter_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendPathData_(Greeter_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::Compile(::grpc::ClientContext* context, const ::LinkCommand::LinkCommandRequest& request, ::LinkCommand::LinkCommandReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Compile_, context, request, response);
}

void Greeter::Stub::experimental_async::Compile(::grpc::ClientContext* context, const ::LinkCommand::LinkCommandRequest* request, ::LinkCommand::LinkCommandReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Compile_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::Compile(::grpc::ClientContext* context, const ::LinkCommand::LinkCommandRequest* request, ::LinkCommand::LinkCommandReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Compile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LinkCommand::LinkCommandReply>* Greeter::Stub::PrepareAsyncCompileRaw(::grpc::ClientContext* context, const ::LinkCommand::LinkCommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::LinkCommand::LinkCommandReply>::Create(channel_.get(), cq, rpcmethod_Compile_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::LinkCommand::LinkCommandReply>* Greeter::Stub::AsyncCompileRaw(::grpc::ClientContext* context, const ::LinkCommand::LinkCommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCompileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::ShouldSendPathData(::grpc::ClientContext* context, const ::LinkCommand::ShouldSendPathDataRequest& request, ::LinkCommand::ShouldSendPathDataReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ShouldSendPathData_, context, request, response);
}

void Greeter::Stub::experimental_async::ShouldSendPathData(::grpc::ClientContext* context, const ::LinkCommand::ShouldSendPathDataRequest* request, ::LinkCommand::ShouldSendPathDataReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ShouldSendPathData_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::ShouldSendPathData(::grpc::ClientContext* context, const ::LinkCommand::ShouldSendPathDataRequest* request, ::LinkCommand::ShouldSendPathDataReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ShouldSendPathData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LinkCommand::ShouldSendPathDataReply>* Greeter::Stub::PrepareAsyncShouldSendPathDataRaw(::grpc::ClientContext* context, const ::LinkCommand::ShouldSendPathDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::LinkCommand::ShouldSendPathDataReply>::Create(channel_.get(), cq, rpcmethod_ShouldSendPathData_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::LinkCommand::ShouldSendPathDataReply>* Greeter::Stub::AsyncShouldSendPathDataRaw(::grpc::ClientContext* context, const ::LinkCommand::ShouldSendPathDataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShouldSendPathDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::SendPathData(::grpc::ClientContext* context, const ::LinkCommand::SendPathDataRequest& request, ::LinkCommand::SendPathDataReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPathData_, context, request, response);
}

void Greeter::Stub::experimental_async::SendPathData(::grpc::ClientContext* context, const ::LinkCommand::SendPathDataRequest* request, ::LinkCommand::SendPathDataReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPathData_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::SendPathData(::grpc::ClientContext* context, const ::LinkCommand::SendPathDataRequest* request, ::LinkCommand::SendPathDataReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPathData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LinkCommand::SendPathDataReply>* Greeter::Stub::PrepareAsyncSendPathDataRaw(::grpc::ClientContext* context, const ::LinkCommand::SendPathDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::LinkCommand::SendPathDataReply>::Create(channel_.get(), cq, rpcmethod_SendPathData_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::LinkCommand::SendPathDataReply>* Greeter::Stub::AsyncSendPathDataRaw(::grpc::ClientContext* context, const ::LinkCommand::SendPathDataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendPathDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::LinkCommand::LinkCommandRequest, ::LinkCommand::LinkCommandReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::LinkCommand::LinkCommandRequest* req,
             ::LinkCommand::LinkCommandReply* resp) {
               return service->Compile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::LinkCommand::ShouldSendPathDataRequest, ::LinkCommand::ShouldSendPathDataReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::LinkCommand::ShouldSendPathDataRequest* req,
             ::LinkCommand::ShouldSendPathDataReply* resp) {
               return service->ShouldSendPathData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::LinkCommand::SendPathDataRequest, ::LinkCommand::SendPathDataReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::LinkCommand::SendPathDataRequest* req,
             ::LinkCommand::SendPathDataReply* resp) {
               return service->SendPathData(ctx, req, resp);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::Compile(::grpc::ServerContext* context, const ::LinkCommand::LinkCommandRequest* request, ::LinkCommand::LinkCommandReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ShouldSendPathData(::grpc::ServerContext* context, const ::LinkCommand::ShouldSendPathDataRequest* request, ::LinkCommand::ShouldSendPathDataReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::SendPathData(::grpc::ServerContext* context, const ::LinkCommand::SendPathDataRequest* request, ::LinkCommand::SendPathDataReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace LinkCommand

